titleOnly: true

types:
  - build
  - chore
  - ci
  - docs
  - feat
  - fix
  - perf
  - refactor
  - revert
  - style
  - test

scopes:
  - eslint-config-kodefox
  - exoflex
  - feetch
  - flexship
  - miflex
  - naviflex
