version: 2.1

orbs:
  compare-url: oshimayoan/compare-url@1.2.4
  cypress: cypress-io/cypress@1.13.0

jobs:
  testing:
    docker:
      - image: circleci/node:8.15.0

    working_directory: ~/repo

    steps:
      - checkout
      - compare-url/reconstruct:
          project-path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "packages/naviflex/yarn.lock" }}
            # fallback to use the latest cache if no exact match is found
            - v1-dependencies-

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "packages/exoflex/yarn.lock" }}
            # fallback to use the latest cache if no exact match is found
            - v1-dependencies-

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "packages/miflex/yarn.lock" }}
            # fallback to use the latest cache if no exact match is found
            - v1-dependencies-

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "packages/flexship/yarn.lock" }}
            # fallback to use the latest cache if no exact match is found
            - v1-dependencies-

      - compare-url/use:
          step-name: Testing Phase
          custom-logic: |
            for ORB in packages/*/; do
              orbname=$(basename $ORB)
              if [[ $(git diff $COMMIT_RANGE --name-status | grep "$orbname") ]]; then
                echo "testing ${orbname}"
                if [ ${orbname} != "naviflex" ]; then
                  cd packages/${orbname}
                  yarn install --frozen-lockfile
                  yarn test --silent --maxWorkers=4
                  cd ../..
                else
                  echo "no need to test this project"
                fi
              else
                echo "${orbname} not modified; no need to test"
              fi
            done

      - save_cache:
          paths:
            - packages/naviflex/node_modules
          key: v1-dependencies-{{ checksum "packages/naviflex/yarn.lock" }}

      - save_cache:
          paths:
            - packages/exoflex/node_modules
          key: v1-dependencies-{{ checksum "packages/exoflex/yarn.lock" }}

      - save_cache:
          paths:
            - packages/miflex/node_modules
          key: v1-dependencies-{{ checksum "packages/miflex/yarn.lock" }}

      - save_cache:
          paths:
            - packages/flexship/node_modules
          key: v1-dependencies-{{ checksum "packages/flexship/yarn.lock" }}

workflows:
  main:
    jobs:
      - testing
      - cypress/run:
          name: Visual Regression Testing
          yarn: true
          post-install:
            - run:
                name: Install exoflex dependencies
                command: |
                  cd packages/exoflex
                  yarn
            - run:
                name: Install Expo CLI
                command: yarn global add expo-cli
          start: yarn web
          command: yarn percy exec -- cypress run
          working_directory: packages/exoflex/example
          cache-key: 'yarn-packages-{{ arch }}-{{ .Branch }}-{{ checksum "packages/exoflex/example/yarn.lock" }}'
          requires:
            - testing
